export const UPDATE_TOTAL_DONATE = 'UPDATE_TOTAL_DONATE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE_BY_ID = 'REMOVE_MESSAGE_BY_ID';
export const LOAD_CHARITIES_SUCCESS = 'LOAD_CHARITIES_SUCCESS';
export const LOAD_PAYMENTS_SUCCESS = 'LOAD_PAYMENTS_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';